export const razasPerros: string[] = [
	"Sin Raza (Especial)",
	"Affenpinscher",
	"Akita",
	"Beagle",
	"Boxer",
	"Bulldog",
	"Chihuahua",
	"Dachshund",
	"Doberman",
	"Golden Retriever",
	"Labrador Retriever",
	"Poodle",
	"Pug",
	"Rottweiler",
	"Schnauzer",
	"Shih Tzu",
	"Yorkshire Terrier",
	"Yorkshire Terrier",
	"Yorkshire Terrier",
	"Yorkshire Terrier",
	"Yorkshire Terrier",
	"Yorkshire Terrier",
	"Yorkshire Terrier",
	"Yorkshire Terrier",
	"Yorkshire Terrier",
	"Yorkshire Terrier",
	"Yorkshire Terrier",
	"Yorkshire Terrier",
	"Yorkshire Terrier",
	"Yorkshire Terrier",
]

export const razasGatos: string[] = [
	"Sin Raza (Especial)",
	"Persa",
	"Siames",
	"Maine Coon",
	"Ragdoll",
	"Bengali",
	"Birmano",
	"Sphynx",
	"Siberiano",
	"Somali"
]