export const razasPerros: string[] = [
	"Sin Raza (Especial)",
    "Affenpinscher",
    "Akita",
    "Basenji",
    "Beauceron",
    "Beagle",
    "Bichón Frisé",
    "Borzoï",
    "Boston Terrier",
    "Boxer",
    "Braco Italiano",
    "Briard",
    "Brittany",
    "Bulldog",
    "Bulldog Americano",
    "Bulldog Francés",
    "Bullmastiff",
    "Bull Terrier Miniatura",
    "Cairn Terrier",
    "Cane Corso",
    "Cardigan Welsh Corgi",
    "Cocker Spaniel Americano",
    "Cocker Spaniel Inglés",
    "Collie",
    "Collie Barbilongo",
    "Coonhound",
    "Coonhound Negro y Tan",
    "Corgi",
    "Corgi Cardigan",
    "Corgi Pembroke",
    "Coton de Tulear",
    "Dachshund",
    "Dálmata",
    "Dandie Dinmont Terrier",
    "Doberman",
    "Dogo Argentino",
    "Dogue de Burdeos",
    "Elkhound Noruego",
    "English Setter",
    "French Bulldog",
    "Galgo",
    "Galgo Italiano",
    "Gran Danés",
    "Gran Pirineo",
    "Havanés",
    "Harrier",
    "Irish Setter",
    "Irish Terrier",
    "Irish Water Spaniel",
    "Irish Wolfhound",
    "Italian Greyhound",
    "Jack Russell Terrier",
    "Japanese Chin",
    "Japanese Spitz",
    "Keeshond",
    "Kerry Blue Terrier",
    "Klee Kai",
    "Koolie",
    "Kuvasz",
    "Labrador Retriever",
    "Lagotto Romagnolo",
    "Lakeland Terrier",
    "Lhasa Apso",
    "Maltés",
    "Manchester Terrier",
    "Mastín",
    "Mastín Napolitano",
    "Mudi",
    "Neapolitan Mastiff",
    "Newfoundland",
    "Norfolk Terrier",
    "Norwegian Buhund",
    "Norwegian Elkhound",
    "Norwich Terrier",
    "Nova Scotia Duck Tolling Retriever",
    "Old English Sheepdog",
    "Otterhound",
    "Papillon",
    "Parson Russell Terrier",
    "Pekinés",
    "Petit Basset Griffon Vendeano",
    "Pharaoh Hound",
    "Plott",
    "Pointer",
    "Polish Lowland Sheepdog",
    "Pomerania",
    "Poodle",
    "Portuguese Water Dog",
    "Pug",
    "Puli",
    "Pumi",
    "Rottweiler",
    "Saluki",
    "Samoyedo",
    "San Bernardo",
    "Schipperke",
    "Schnauzer",
    "Scottish Deerhound",
    "Scottish Terrier",
    "Sealyham Terrier",
    "Shiba Inu",
    "Shih Tzu",
    "Siberian Husky",
    "Silky Terrier",
    "Skye Terrier",
    "Sloughi",
    "Small Munsterlander Pointer",
    "Soft Coated Wheaten Terrier",
    "Spanish Water Dog",
    "Springer Spaniel",
    "Staffordshire Bull Terrier",
    "Standard Schnauzer",
    "Sussex Spaniel",
    "Swedish Vallhund",
    "Tibetan Mastiff",
    "Tibetan Spaniel",
    "Tibetan Terrier",
    "Toy Fox Terrier",
    "Vizsla",
    "Weimaraner",
    "Welsh Springer Spaniel",
    "Welsh Terrier",
    "West Highland White Terrier",
    "Whippet",
    "Wire Fox Terrier",
    "Wirehaired Pointing Griffon",
    "Xoloitzcuintli",
    "Yorkshire Terrier"
];

export const razasGatos: string[] = [
	"Sin Raza (Especial)",
	"Abisinio",
    "American Shorthair",
    "American Wirehair",
    "Balinese",
    "Bengalí",
    "Birmano",
    "Bobtail Japonés",
    "Bombay",
    "British Longhair",
    "British Shorthair",
    "Burmés",
    "Chartreux",
    "Cornish Rex",
    "Devon Rex",
    "Egipcio Mau",
    "Himalayo",
    "Maine Coon",
    "Manx",
    "Munchkin",
    "Norwegian Forest",
    "Oriental",
    "Persa",
    "Ragdoll",
    "Siberiano",
    "Siamés",
    "Sokoke",
    "Sphynx",
    "Turco Angora",
    "Turco Van",
    "Singapura",
    "LaPerm",
    "Khao Manee",
    "Korat",
    "Savannah",
    "Scottish Fold",
    "Somalí"
];
